services:
  - type: web
    name: fantasy-contest-tracker
    env: node
    plan: free
    branch: master
    buildCommand: npm install && npm run build:prod
    startCommand: npm run start:prod
    envVars:
      - key: JWT_SECRET
        sync: true
      - key: NODE_ENV
        value: production
    autoDeploy: true
