services:
  - type: web
    name: fantasy-contest-tracker
    env: node
    plan: free
    branch: master
    buildCommand: npm install --include=dev && node --max-old-space-size=512 ./node_modules/@angular/cli/bin/ng build --configuration production
    startCommand: npm run start:prod
    envVars:
      - key: JWT_SECRET
        sync: true
      - key: NODE_ENV
        value: production
    autoDeploy: true
